name: Go App Base Workflow

on:
  push:
    branches:
      - Go_APP_Base
  pull_request:
    branches:
      - Go_APP_Base

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint pylint-exit

      - name: Verify pylint is installed
        run: |
          pylint --version
          which pylint

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py') --fail-under=9.85 || pylint-exit $?

      - name: Run the script with SECRET_KEY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest test/ui/testcases/test_home_screen.py
        
