name: Go App Base Workflow

on:
  push:
    branches:
      - Go_APP_Base
  pull_request:
    branches:
      - Go_APP_Base

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate environment variables
        run: |
          if [ -z "$LT_USERNAME" ]; then echo "LT_USERNAME is not set!"; exit 1; fi
          if [ -z "$LT_ACCESS_KEY" ]; then echo "LT_ACCESS_KEY is not set!"; exit 1; fi
          if [ -z "$SECRET_KEY" ]; then echo "SECRET_KEY is not set!"; exit 1; fi

      - name: Run tests with LambdaTest
        env:
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          pytest test/ui/testcases/test_home_screen.py --alluredir=TestResults/allure-reports \
            --base-url="https://${{ secrets.LT_USERNAME }}:${{ secrets.LT_ACCESS_KEY }}@mobile-hub.lambdatest.com/wd/hub"

      - name: Publish Allure Reports
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: TestResults/allure-reports

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: path/to/screenshots/or/logs